"""Shiyi public API."""

from shiyi.adapters.anthropic import AnthropicNewsAdapter, anthropic_news_adapter
from shiyi.adapters.bytedance_seed import ByteDanceSeedBlogAdapter, bytedance_seed_blog_adapter
from shiyi.adapters.changelog import (
    ArticleDetail,
    ArticleIndexEntry,
    ChangelogEntry,
    ChangelogPageAdapter,
    OfficialArticleAdapter,
    cohere_blog_adapter,
    deepseek_news_adapter,
    deepseek_updates_adapter,
    gemini_api_changelog_adapter,
    mistral_news_adapter,
    moonshot_kimi_changelog_adapter,
    z_ai_blog_adapter,
    z_ai_release_notes_adapter,
)
from shiyi.adapters.deepmind import DeepMindArticle, DeepMindBlogAdapter, deepmind_blog_adapter
from shiyi.adapters.rss import (
    RssDetailAdapter,
    RssDetailArticle,
    RssFeedAdapter,
    google_research_blog_adapter,
    huggingface_blog_adapter,
    microsoft_ai_blog_adapter,
    openai_news_adapter,
)
from shiyi.domain.models import (
    ArtifactRead,
    ArtifactRef,
    ArtifactWrite,
    BinaryPayload,
    CaptureWindow,
    ClassifyTask,
    ContentDepth,
    EnrichmentResult,
    EventRecord,
    ExtractTask,
    HtmlPayload,
    InternalItem,
    ModelIdentity,
    Provenance,
    SourceIdentity,
    SummarizeTask,
    TextPayload,
    TokenUsage,
    content_depth_from_metadata,
    is_source_ready_content_depth,
    payload_content_hash,
)
from shiyi.export import ExportedItem, export_items
from shiyi.normalizers.html import HtmlMarkdownNormalizer
from shiyi.pipeline.runner import CapturePipeline, PipelineRunError, PipelineRunSummary
from shiyi.ports.adapter import Adapter
from shiyi.ports.ai_provider import AIProvider
from shiyi.ports.artifact_store import ArtifactStore
from shiyi.ports.event_record_store import EventRecordStore
from shiyi.ports.normalizer import Normalizer
from shiyi.sources import (
    BUILTIN_SOURCE_NAMES,
    SOURCE_BACKLOG,
    SOURCE_DEFINITIONS,
    DetailCaptureMode,
    ReadinessStatus,
    SourceBacklogItem,
    SourceClass,
    SourceDefinition,
    SourceName,
    SourceSummary,
    build_source_adapter,
    iter_builtin_sources,
    iter_source_backlog,
    source_definition,
    source_summaries,
)

__all__ = [
    "BUILTIN_SOURCE_NAMES",
    "SOURCE_BACKLOG",
    "SOURCE_DEFINITIONS",
    "AIProvider",
    "Adapter",
    "AnthropicNewsAdapter",
    "ArticleDetail",
    "ArticleIndexEntry",
    "ArtifactRead",
    "ArtifactRef",
    "ArtifactStore",
    "ArtifactWrite",
    "BinaryPayload",
    "ByteDanceSeedBlogAdapter",
    "CapturePipeline",
    "CaptureWindow",
    "ChangelogEntry",
    "ChangelogPageAdapter",
    "ClassifyTask",
    "ContentDepth",
    "DeepMindArticle",
    "DeepMindBlogAdapter",
    "DetailCaptureMode",
    "EnrichmentResult",
    "EventRecord",
    "EventRecordStore",
    "ExportedItem",
    "ExtractTask",
    "HtmlMarkdownNormalizer",
    "HtmlPayload",
    "InternalItem",
    "ModelIdentity",
    "Normalizer",
    "OfficialArticleAdapter",
    "PipelineRunError",
    "PipelineRunSummary",
    "Provenance",
    "ReadinessStatus",
    "RssDetailAdapter",
    "RssDetailArticle",
    "RssFeedAdapter",
    "SourceBacklogItem",
    "SourceClass",
    "SourceDefinition",
    "SourceIdentity",
    "SourceName",
    "SourceSummary",
    "SummarizeTask",
    "TextPayload",
    "TokenUsage",
    "anthropic_news_adapter",
    "build_source_adapter",
    "bytedance_seed_blog_adapter",
    "cohere_blog_adapter",
    "content_depth_from_metadata",
    "deepmind_blog_adapter",
    "deepseek_news_adapter",
    "deepseek_updates_adapter",
    "export_items",
    "gemini_api_changelog_adapter",
    "google_research_blog_adapter",
    "huggingface_blog_adapter",
    "is_source_ready_content_depth",
    "iter_builtin_sources",
    "iter_source_backlog",
    "microsoft_ai_blog_adapter",
    "mistral_news_adapter",
    "moonshot_kimi_changelog_adapter",
    "openai_news_adapter",
    "payload_content_hash",
    "source_definition",
    "source_summaries",
    "z_ai_blog_adapter",
    "z_ai_release_notes_adapter",
]
